microserviceName: "inventory"

image:
  repository: iga1playeconomy.azurecr.io/play.inventory
  tag: 1.0.4

envVariables:
  ServiceSettings__Authority: https://iga1playeconomy.eastus.cloudapp.azure.com/identity-svc

resources:
  limits:
    memory: "128Mi"
    cpu: "150m"

container:
  port: 5004

service:
  type: ClusterIP
  port: 80
